# Generated by Django 3.2.6 on 2023-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
