# Generated by Django 3.2.6 on 2023-10-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('Dean', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('school_description', models.TextField(max_length=300)),
                ('slugy', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='navapp.school'),
        ),
    ]
