# Generated by Django 3.2.6 on 2023-11-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0003_auto_20231031_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='slugy',
            new_name='slug',
        ),
    ]
