# Generated by Django 3.2.6 on 2023-11-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0004_rename_slugy_school_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='slug',
            new_name='slugy',
        ),
    ]
