# Generated by Django 3.2.6 on 2023-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0005_rename_slug_school_slugy'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
