# Generated by Django 3.2.6 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_description',
            field=models.TextField(),
        ),
    ]
