# Generated by Django 3.2.6 on 2023-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0008_alter_school_school_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
